version: "3.9"
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password123'
      MYSQL_ROOT_PASSWORD: 'passwordroot'
    ports:
      - '3306:3306'

