"""Initial book

Revision ID: c858aa96ab9b
Revises: c9320dd8d15f
Create Date: 2021-10-04 23:32:27.085592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c858aa96ab9b'
down_revision = 'c9320dd8d15f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('book_id', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'book_id')
    # ### end Alembic commands ###
